export const schema = {
  type: 'object',
  properties: {
    __common__: {
      type: 'boolean',
      description: '是否启用通用配置',
    },
    cookie: { type: 'string' },
    accessKey: { type: 'string' },
    createCookieDay: { type: 'number' },
    message: {
      type: 'object',
      properties: {
        br: { type: 'string' },
        onlyError: { type: 'boolean' },
        email: {
          type: 'object',
          properties: {
            host: { type: 'string' },
            port: { type: 'number' },
            from: { type: 'string' },
            to: { type: 'string' },
            pass: { type: 'string' },
          },
          required: ['pass', 'from'],
        },
        pushplusToken: { type: 'string' },
        api: {
          type: 'object',
          properties: {
            method: { type: 'string' },
            headers: { type: 'object' },
            timeout: { type: 'number' },
            url: { type: 'string' },
            proxy: {
              type: 'object',
              properties: {
                host: { type: 'string' },
                port: { type: 'number' },
                auth: { type: 'string' },
              },
              required: ['host', 'port'],
            },
            data: { type: 'object' },
          },
        },
      },
    },
    function: {
      type: 'object',
      properties: {
        silver2Coin: { type: 'boolean' },
        liveSignTask: { type: 'boolean' },
        addCoins: { type: 'boolean' },
        shareAndWatch: { type: 'boolean' },
        supGroupSign: { type: 'boolean' },
        useCouponBp: { type: 'boolean' },
        charging: { type: 'boolean' },
        getVipPrivilege: { type: 'boolean' },
        giveGift: { type: 'boolean' },
        matchGame: { type: 'boolean' },
        liveLottery: { type: 'boolean' },
        liveRedPack: { type: 'boolean' },
        batchUnfollow: { type: 'boolean' },
        liveIntimacy: { type: 'boolean' },
        mangaTask: { type: 'boolean' },
        bigPoint: { type: 'boolean' },
        judgement: { type: 'boolean' },
        activityLottery: { type: 'boolean' },
        dailyBattery: { type: 'boolean' },
        liveWeekTask: { type: 'boolean' },
        blink: { type: 'boolean' },
        watchLink: { type: 'boolean' },
        liveDm: { type: 'boolean' },
      },
    },
    log: {
      type: 'object',
      properties: {
        pushLevel: { type: 'string' },
        consoleLevel: { type: 'string' },
        fileLevel: { type: 'string' },
        useEmoji: { type: 'boolean' },
        fileSplit: { type: 'string' },
      },
    },
    limit: {
      type: 'object',
      properties: {
        level6: { type: 'boolean' },
        coins5: { type: 'boolean' },
      },
    },
    apiDelay: {
      type: 'array',
      items: { type: 'number' },
    },
    userAgent: { type: 'string' },
    dailyRunTime: { type: 'string' },
    match: {
      type: 'object',
      properties: {
        coins: { type: 'number' },
        selection: { type: 'number' },
        diff: { type: 'number' },
      },
    },
    charge: { type: 'object' },
    couponBalance: {
      type: 'object',
      properties: {
        mid: { type: 'number' },
        presetTime: { type: 'array', items: { type: 'number' } },
        use: { type: 'string' },
      },
    },
    gift: {
      type: 'object',
      description: '礼物配置',
      properties: {
        mids: { type: 'array', items: { type: 'number' } },
        id: { type: 'array', items: { type: 'number' } },
        name: { type: 'array', items: { type: 'string' } },
        all: { type: 'boolean' },
        expire: { type: 'boolean' },
      },
    },
    coin: {
      type: 'object',
      properties: {
        customizeUp: { type: 'array', items: { type: 'number' } },
        targetLevel: { type: 'number' },
        stayCoins: { type: 'number' },
        targetCoins: { type: 'number' },
        upperAccMatch: { type: 'boolean' },
        src: { type: 'array', items: { type: 'string' } },
      },
    },
    lottery: {
      type: 'object',
      properties: {
        excludeAward: { type: 'array', items: { type: 'number' } },
        includeAward: { type: 'array', items: { type: 'number' } },
        blackUid: { type: 'array', items: { type: 'number' } },
        moveTag: { type: 'string' },
        pageNum: { type: 'number' },
        actFollowMsg: { type: 'string' },
        scanFollow: { type: 'string' },
        skipNeedFollow: { type: 'boolean' },
        mayBeWinMsg: { type: 'boolean' },
      },
    },
    redPack: {
      type: 'object',
      properties: {
        source: { type: 'number' },
        uri: { type: 'string' },
        intervalActive: { type: 'number' },
        restTime: { type: 'array', items: { type: 'number' } },
        riskTime: { type: 'array', items: { type: 'number' } },
        riskSleepTime: { type: 'number' },
        linkRoomNum: { type: 'number' },
        totalNum: { type: 'number' },
        dmNum: { type: 'array', items: { type: 'number' } },
        moveUpInWait: { type: 'boolean' },
        moveTag: { type: 'string' },
        actFollowMsg: { type: 'string' },
        noWinNum: { type: 'number' },
        riskNum: { type: 'number' },
      },
    },
    unFollow: {
      type: 'object',
      properties: {
        delay: { type: 'number' },
        restTime: { type: 'array', items: { type: 'number' } },
        totalNum: { type: 'number' },
        tags: { type: 'array', items: { type: 'string' } },
      },
    },
    intimacy: {
      type: 'object',
      properties: {
        liveSendMessage: { type: 'boolean' },
        liveLike: { type: 'boolean' },
        liveHeart: { type: 'boolean' },
        whiteList: { type: 'array', items: { type: 'number' } },
        blackList: { type: 'array', items: { type: 'number' } },
        limitFeed: { type: 'number' },
        skipNum: { type: 'number' },
        isRetryHeart: { type: 'boolean' },
        dm: { type: 'object' },
      },
    },
    jury: {
      type: 'object',
      properties: {
        once: { type: 'boolean' },
        vote: { type: 'array', items: { type: 'number' } },
        opinion: { type: 'boolean' },
        opinionMin: { type: 'number' },
        notOpinion: { type: 'array', items: { type: 'number' } },
        waitTime: { type: 'number' },
        insiderWeight: { type: 'number' },
        insiders: { type: 'array', items: { type: 'number' } },
        anonymous: { type: 'array', items: { type: 'number' } },
        newTrigger: { type: 'boolean' },
        async: { type: 'boolean' },
      },
    },
    manga: {
      type: 'object',
      properties: {
        sign: { type: 'boolean' },
        buy: { type: 'boolean' },
        read: { type: 'boolean' },
        mc: { type: 'array', items: { type: 'number' } },
        name: { type: 'array', items: { type: 'string' } },
        love: { type: 'boolean' },
      },
    },
    exchangeCoupon: {
      type: 'object',
      properties: {
        num: { type: 'number' },
        delay: { type: 'number' },
        keepAmount: { type: 'number' },
        startHour: { type: 'number' },
      },
    },
    exchangeBigPoint: {
      type: 'object',
      properties: {
        delay: { type: 'number' },
        retry: { type: 'number' },
        startDelay: { type: 'number' },
        name: { type: 'array', items: { type: 'string' } },
        token: { type: 'array', items: { type: 'string' } },
      },
    },
    bigPoint: {
      type: 'object',
      properties: {
        isRetry: { type: 'number' },
        isWatch: { type: 'boolean' },
        watchDelay: { type: 'number' },
      },
    },
    activityLottery: {
      type: 'object',
      properties: {
        list: { type: 'array', items: { type: 'number' } },
        isRequest: { type: 'boolean' },
        delay: { type: 'array', items: { type: 'number' } },
        bangumi: { type: 'boolean' },
        follow: { type: 'boolean' },
        proxyPrefix: { type: 'string' },
        customUrl: { type: 'string' },
      },
    },
    watchLink: {
      type: 'object',
      properties: {
        uid: { type: 'array', items: { type: 'number' } },
        roomid: { type: 'array', items: { type: 'number' } },
        heart: { type: 'boolean' },
        time: { type: 'number' },
        wss: { type: 'boolean' },
        tcp: { type: 'boolean' },
        parentId: { type: 'number' },
        areaId: { type: 'number' },
        area: { type: 'array', items: { type: 'array', items: { type: 'number' } } },
      },
    },
    liveDm: {
      type: 'object',
      properties: {
        roomid: { type: 'array', items: { type: 'number' } },
        delay: { type: 'array', items: { type: 'number' } },
        num: { type: 'number' },
        custom: { type: 'array' },
      },
    },
    blink: {
      type: 'object',
      properties: {
        title: { type: 'string' },
        parentId: { type: 'number' },
        areaId: { type: 'number' },
        roomid: { type: 'number' },
        time: { type: 'number' },
      },
    },
    app: {
      type: 'object',
      properties: {
        http: { type: 'object' },
      },
    },
    dailyBattery: {
      type: 'object',
      properties: {
        task39: { type: 'boolean' },
        task34: { type: 'boolean' },
      },
    },
  },
};

export const arrSchema = {
  type: 'array',
  items: schema,
};
