// https://api.live.bilibili.com/xlive/web-interface/v1/index/getWebAreaList?source_id=2

export const options = [
  {
    label: '英雄联盟',
    value: '86',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '无畏契约',
    value: '329',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'CS:GO',
    value: '89',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'APEX英雄',
    value: '240',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '永劫无间',
    value: '666',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '穿越火线',
    value: '88',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '命运方舟',
    value: '590',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'DOTA2',
    value: '92',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '吃鸡行动',
    value: '80',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '逃离塔科夫',
    value: '252',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '传奇',
    value: '695',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'DNF',
    value: '78',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '卡拉彼丘',
    value: '782',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '幕后高手',
    value: '774',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '生死狙击2',
    value: '575',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '洛奇英雄传',
    value: '599',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '七日世界',
    value: '857',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '最终幻想14',
    value: '102',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '重生边缘',
    value: '809',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '星际战甲',
    value: '249',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '梦三国',
    value: '710',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '英魂之刃',
    value: '690',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '剑网3',
    value: '82',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '从军',
    value: '829',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '全民街篮',
    value: '845',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '铁甲雄兵',
    value: '691',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '新天龙八部',
    value: '653',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '赛尔号',
    value: '667',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '造梦西游',
    value: '668',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '洛克王国',
    value: '669',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '问道',
    value: '670',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '诛仙世界',
    value: '654',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '大话西游',
    value: '652',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '奇迹MU',
    value: '683',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '永恒之塔',
    value: '684',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'QQ三国',
    value: '685',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '人间地狱',
    value: '677',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '彩虹岛',
    value: '686',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '洛奇',
    value: '663',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '跑跑卡丁车',
    value: '664',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '星际公民',
    value: '658',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'Squad战术小队',
    value: '659',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '反恐精英Online',
    value: '629',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '创世战车',
    value: '705',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '装甲战争',
    value: '642',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '守望先锋',
    value: '87',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '阿尔比恩',
    value: '639',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '猎杀对决',
    value: '600',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'CFHD',
    value: '472',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '武装突袭',
    value: '634',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '300英雄',
    value: '84',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '炉石传说',
    value: '91',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '剑网3缘起',
    value: '499',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '街头篮球',
    value: '649',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '综合射击',
    value: '601',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '剑灵',
    value: '505',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '黑色沙漠',
    value: '632',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '天涯明月刀',
    value: '596',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '冒险岛',
    value: '574',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '逆战',
    value: '487',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '魔兽争霸3',
    value: '181',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'QQ飞车',
    value: '610',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '魔兽世界',
    value: '83',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'NBA2KOL2',
    value: '581',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '使命召唤:战区',
    value: '318',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '坦克世界',
    value: '115',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '战舰世界',
    value: '248',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '战争雷霆',
    value: '316',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '战意',
    value: '383',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '风暴英雄',
    value: '114',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '星际争霸2',
    value: '93',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '刀塔自走棋',
    value: '239',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '堡垒之夜',
    value: '164',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '枪神纪',
    value: '251',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '三国杀',
    value: '81',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '龙之谷',
    value: '112',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '幻想全明星',
    value: '176',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '怀旧网游',
    value: '288',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '新游前瞻',
    value: '298',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '星战前夜：晨曦',
    value: '331',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '流放之路',
    value: '551',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'FPS沙盒',
    value: '633',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '永恒轮回',
    value: '459',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '激战2',
    value: '607',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '其他网游',
    value: '107',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '蓝色协议',
    value: '760',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: 'The Finals',
    value: '846',
    parentId: '2',
    parentName: '网游',
  },
  {
    label: '王者荣耀',
    value: '35',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '和平精英',
    value: '256',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '原神',
    value: '321',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '崩坏：星穹铁道',
    value: '549',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '第五人格',
    value: '163',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '绝区零',
    value: '662',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'LOL手游',
    value: '395',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '明日方舟',
    value: '255',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '黎明觉醒：生机',
    value: '479',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '蛋仔派对',
    value: '571',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '元梦之星',
    value: '822',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '闪耀！优俊少女',
    value: '805',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '白荆回廊',
    value: '849',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '元气骑士前传',
    value: '850',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '光隙解语',
    value: '853',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '钢岚',
    value: '856',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '众神派对',
    value: '861',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '极品飞车在线移动版',
    value: '852',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '女神异闻录：夜幕魅影',
    value: '802',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '依露希尔：星晓',
    value: '838',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '斯露德',
    value: '797',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '千年之旅',
    value: '806',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '白夜极光',
    value: '781',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '逆水寒手游',
    value: '771',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '率土之滨',
    value: '807',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '萤火突击',
    value: '870',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '绯色回响',
    value: '837',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '月圆之夜',
    value: '215',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '哈利波特：魔法觉醒',
    value: '474',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '七人传奇',
    value: '823',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '幻塔',
    value: '550',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '星之破晓',
    value: '799',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '金铲铲之战',
    value: '514',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '少女前线2：追放',
    value: '832',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '深空之眼',
    value: '598',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '交错战线',
    value: '864',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '无期迷途',
    value: '675',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '超进化物语2',
    value: '862',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '晶核',
    value: '777',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '星球重启',
    value: '828',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '光遇',
    value: '687',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '桃源深处有人家',
    value: '792',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '三国志战棋版',
    value: '756',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '以闪亮之名',
    value: '755',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '尘白禁区',
    value: '778',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '鬼泣-巅峰之战',
    value: '470',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '香肠派对',
    value: '689',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '高能英雄',
    value: '783',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '使命召唤手游',
    value: '386',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '崩坏3',
    value: '40',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '蔚蓝档案',
    value: '787',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '第七史诗',
    value: '784',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '游戏王：决斗链接',
    value: '407',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '游戏王',
    value: '303',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'JJ斗地主',
    value: '724',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '阴阳师',
    value: '36',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '欢乐斗地主',
    value: '719',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '太空杀',
    value: '791',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '长安幻想',
    value: '738',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '火影忍者手游',
    value: '292',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'Fate/GO',
    value: '37',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '综合棋牌',
    value: '354',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'QQ飞车手游',
    value: '154',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '决战！平安京',
    value: '140',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '狼人杀',
    value: '41',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '三国杀移动版',
    value: '352',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '碧蓝航线',
    value: '113',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '影之诗',
    value: '156',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '明日之后',
    value: '189',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '重返未来：1999',
    value: '761',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '环行旅舍',
    value: '786',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '幻世与冒险',
    value: '813',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '部落冲突:皇室战争',
    value: '50',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '奥比岛手游',
    value: '661',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '弹弹堂',
    value: '734',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '雀姬',
    value: '214',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '公主连结Re:Dive',
    value: '330',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'DNF手游',
    value: '343',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'FIFA足球世界',
    value: '641',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'BanG Dream',
    value: '258',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '荒野乱斗',
    value: '469',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: 'CF手游',
    value: '333',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '战双帕弥什',
    value: '293',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '天涯明月刀手游',
    value: '389',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '解密游戏',
    value: '42',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '恋爱养成游戏',
    value: '576',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '暗黑破坏神：不朽',
    value: '492',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '暗区突围',
    value: '502',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '跑跑卡丁车手游',
    value: '265',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '非人学园',
    value: '212',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '百闻牌',
    value: '286',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '猫和老鼠手游',
    value: '269',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '坎公骑冠剑',
    value: '442',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '忍者必须死3',
    value: '203',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '梦幻西游手游',
    value: '342',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '航海王热血航线',
    value: '504',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '少女前线',
    value: '39',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '300大作战',
    value: '688',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '少女前线：云图计划',
    value: '525',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '漫威超级战争',
    value: '478',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '摩尔庄园手游',
    value: '464',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '宝可梦大集结',
    value: '493',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '小动物之星',
    value: '473',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '天地劫：幽城再临',
    value: '448',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '漫威对决',
    value: '511',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '东方归言录',
    value: '538',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '梦幻模拟战',
    value: '178',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '时空猎人3',
    value: '643',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '重返帝国',
    value: '613',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '休闲小游戏',
    value: '679',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '其他手游',
    value: '98',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '山海镜花',
    value: '821',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '小冰冰传奇',
    value: '824',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '冒险岛手游',
    value: '796',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '新游评测',
    value: '274',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '对峙2',
    value: '863',
    parentId: '3',
    parentName: '手游',
  },
  {
    label: '主机游戏',
    value: '236',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '其他单机',
    value: '235',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '独立游戏',
    value: '283',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '怀旧游戏',
    value: '237',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '恐怖游戏',
    value: '276',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '幻兽帕鲁',
    value: '866',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '猛兽派对',
    value: '384',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '命运2',
    value: '277',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: 'FORZA 极限竞速',
    value: '302',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '卡牌潮玩',
    value: '854',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '我的世界',
    value: '216',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '铁拳8',
    value: '867',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '全境封锁2',
    value: '243',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '雾锁王国',
    value: '869',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '植物大战僵尸',
    value: '309',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '暖雪',
    value: '582',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '雀魂麻将',
    value: '803',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '怪物猎人',
    value: '578',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '使命召唤20',
    value: '282',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '生化危机',
    value: '721',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '战地风云',
    value: '597',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '格斗游戏',
    value: '433',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '精灵宝可梦',
    value: '228',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '碧蓝幻想GBR',
    value: '859',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '红色警戒2',
    value: '693',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '策略游戏',
    value: '570',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '艾尔登法环',
    value: '555',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '暗黑破坏神Ⅳ',
    value: '780',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '为了吾王II',
    value: '769',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '宝可梦集换式卡牌游戏',
    value: '720',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '饥荒',
    value: '218',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '荒野大镖客2',
    value: '226',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '塞尔达传说',
    value: '308',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '方舟',
    value: '295',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '帝国时代4',
    value: '548',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '体育游戏',
    value: '500',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: 'Dark and Darker',
    value: '795',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '仁王2',
    value: '313',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '只狼',
    value: '245',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '暗黑破坏神',
    value: '535',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: 'FC24',
    value: '830',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '以撒',
    value: '219',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '泰拉瑞亚',
    value: '593',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '骑马与砍杀',
    value: '326',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '斯普拉遁3',
    value: '694',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '刺客信条',
    value: '227',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: 'Dread Hunger',
    value: '591',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '恋爱模拟游戏',
    value: '592',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: 'NBA2K',
    value: '362',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '游戏速通',
    value: '678',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '博德之门3',
    value: '385',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '全面战争：战锤3',
    value: '594',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '双人成行',
    value: '446',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '赛博朋克2077',
    value: '402',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '糖豆人',
    value: '357',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '聚会游戏',
    value: '636',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '全面战争',
    value: '257',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '德州电锯',
    value: '834',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '重生细胞',
    value: '426',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '辐射76',
    value: '220',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '战神',
    value: '579',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '匹诺曹的谎言',
    value: '812',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '鬼泣5',
    value: '244',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '恐鬼症',
    value: '387',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '消逝的光芒2',
    value: '586',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: 'Roblox',
    value: '753',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '无主之地3',
    value: '273',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '边境',
    value: '763',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '索尼克SuperStar',
    value: '844',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '胡闹厨房',
    value: '507',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '盗贼之海',
    value: '341',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: 'KARDS',
    value: '835',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '收获日3',
    value: '811',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '致命公司',
    value: '858',
    parentId: '6',
    parentName: '单机游戏',
  },
  {
    label: '萌宅领域',
    value: '530',
    parentId: '1',
    parentName: '娱乐',
  },
  {
    label: '视频唱见',
    value: '21',
    parentId: '1',
    parentName: '娱乐',
  },
  {
    label: '舞见',
    value: '207',
    parentId: '1',
    parentName: '娱乐',
  },
  {
    label: '颜值',
    value: '145',
    parentId: '1',
    parentName: '娱乐',
  },
  {
    label: '脱口秀',
    value: '868',
    parentId: '1',
    parentName: '娱乐',
  },
  {
    label: '唱见电台',
    value: '190',
    parentId: '5',
    parentName: '电台',
  },
  {
    label: '聊天电台',
    value: '192',
    parentId: '5',
    parentName: '电台',
  },
  {
    label: '男声电台',
    value: '817',
    parentId: '5',
    parentName: '电台',
  },
  {
    label: '虚拟Singer',
    value: '744',
    parentId: '9',
    parentName: '虚拟主播',
  },
  {
    label: '虚拟Gamer',
    value: '745',
    parentId: '9',
    parentName: '虚拟主播',
  },
  {
    label: '虚拟声优',
    value: '746',
    parentId: '9',
    parentName: '虚拟主播',
  },
  {
    label: '虚拟男V',
    value: '851',
    parentId: '9',
    parentName: '虚拟主播',
  },
  {
    label: '虚拟日常',
    value: '371',
    parentId: '9',
    parentName: '虚拟主播',
  },
  {
    label: '虚拟APEX',
    value: '789',
    parentId: '9',
    parentName: '虚拟主播',
  },
  {
    label: '虚拟PK',
    value: '775',
    parentId: '9',
    parentName: '虚拟主播',
  },
  {
    label: '交友',
    value: '818',
    parentId: '14',
    parentName: '聊天室',
  },
  {
    label: '点唱',
    value: '819',
    parentId: '14',
    parentName: '聊天室',
  },
  {
    label: '兴趣',
    value: '820',
    parentId: '14',
    parentName: '聊天室',
  },
  {
    label: '生活分享',
    value: '646',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '聊天交友',
    value: '825',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '手工绘画',
    value: '627',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '情感',
    value: '623',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '户外',
    value: '368',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '萌宠',
    value: '369',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '运动',
    value: '628',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '美食',
    value: '367',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '时尚',
    value: '378',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '电子榨菜',
    value: '624',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '沉浸体验',
    value: '827',
    parentId: '10',
    parentName: '生活',
  },
  {
    label: '社科法律心理',
    value: '376',
    parentId: '11',
    parentName: '知识',
  },
  {
    label: '人文历史',
    value: '702',
    parentId: '11',
    parentName: '知识',
  },
  {
    label: '校园学习',
    value: '372',
    parentId: '11',
    parentName: '知识',
  },
  {
    label: '职场·技能',
    value: '377',
    parentId: '11',
    parentName: '知识',
  },
  {
    label: '科技',
    value: '375',
    parentId: '11',
    parentName: '知识',
  },
  {
    label: '科学科普',
    value: '701',
    parentId: '11',
    parentName: '知识',
  },
  {
    label: '时政',
    value: '715',
    parentId: '11',
    parentName: '知识',
  },
  {
    label: '游戏赛事',
    value: '561',
    parentId: '13',
    parentName: '赛事',
  },
  {
    label: '体育赛事',
    value: '562',
    parentId: '13',
    parentName: '赛事',
  },
  {
    label: '赛事综合',
    value: '563',
    parentId: '13',
    parentName: '赛事',
  },
  {
    label: '热门帮玩',
    value: '301000',
    parentId: '301',
    parentName: '帮我玩',
  },
  {
    label: '手游帮玩',
    value: '301002',
    parentId: '301',
    parentName: '帮我玩',
  },
  {
    label: '网游帮玩',
    value: '301003',
    parentId: '301',
    parentName: '帮我玩',
  },
  {
    label: '单机帮玩',
    value: '301004',
    parentId: '301',
    parentName: '帮我玩',
  },
  {
    label: '竞技玩法',
    value: '815',
    parentId: '15',
    parentName: '互动玩法',
  },
  {
    label: '养成玩法',
    value: '840',
    parentId: '15',
    parentName: '互动玩法',
  },
  {
    label: '棋牌玩法',
    value: '841',
    parentId: '15',
    parentName: '互动玩法',
  },
  {
    label: '休闲玩法',
    value: '816',
    parentId: '15',
    parentName: '互动玩法',
  },
  {
    label: '搞笑整蛊',
    value: '842',
    parentId: '15',
    parentName: '互动玩法',
  },
  {
    label: '购物',
    value: '300000',
    parentId: '300',
    parentName: '购物',
  },
];
